server:
  port: 80

spring:
  redis:
    host: 47.99.205.180
    port: 6379
    database: 8
    timeout: 10000
    password: qazwsx
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

## 微信服务器校验token
weichat:
  appId: wx62cdadd6ca450a10
  appSecret: e24ec8e5bdd56aaaf6b1976edcf47db1
  check:
    token: zhaojun


