server:
  port: 80

spring:
  redis:
    host: //todo
    port: 6379
    database: 8
    timeout: 10000
    password: //todo
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

## 微信服务器校验token
weichat:
  appId: //todo
  appSecret: //todo
  check:
    token: zhaojun

